[package]
name = "trading"
version = "0.1.0"
authors = ["furioncycle <ttecho2021@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.3", features = ["router", "desktop"] }
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] } # No wasm-bindgen for desktop-only
serde_json = "1.0.148"
dioxus-desktop = "0.7.3"
chrono = { version = "0.4", features = ["serde"] }
plotters = "0.3"
image = "0.25" # For encoding plotters output to PNG
base64 = "0.22" # For encoding image data to Base64
rand = "0.8.5"
