[application]
name = "gemini"
default_platform = "desktop"

[web.app]
# HTML title tag content
title = "trading"

# include `assets` in web platform
[web.resource]
# Style tag for additional css style files
style = []

# Script tag for additional JavaScript files
script = []

[web.resource.dev]
# Script tag for JavaScript code file
# serve: [dev-server] only
script = []

[build]
tailwind = true
