[application]
name = "gemini"
default_platform = "desktop"

[web.app]
# HTML title tag content
title = "trading"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[build]
tailwind = true
